---
- hosts: all
  become: yes

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      apt:
        name:
          - build-essential
          - cmake
          - libgtk-3-dev
          - libsdl2-dev
          - git
          - nginx
        state: present

    - name: Clone VBA-M repository
      git:
        repo: https://github.com/visualboyadvance-m/visualboyadvance-m.git
        dest: /opt/visualboyadvance-m

    - name: Build and install VBA-M
      shell: |
        cd /opt/visualboyadvance-m
        mkdir -p build
        cd build
        cmake ..
        make -j$(nproc)
        make install
      args:
        creates: /usr/local/bin/vbam

    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
